# Generated by Django 3.1.2 on 2021-07-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20210723_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementteamrecs',
            name='content_writing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managementteamrecs',
            name='media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managementteamrecs',
            name='web',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='roll_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='webteamrecs',
            name='skills',
            field=models.TextField(max_length=3000),
        ),
    ]
