# Generated by Django 3.1.2 on 2020-12-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusAmbassador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll_number', models.CharField(max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('college', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=40)),
                ('year_of_study', models.CharField(max_length=30)),
                ('best_suited', models.CharField(max_length=400)),
                ('key_strengths', models.CharField(max_length=400)),
                ('anticipate_learning', models.CharField(max_length=400)),
                ('past_experience', models.CharField(max_length=400)),
            ],
        ),
    ]
