# Generated by Django 3.1.2 on 2020-12-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Startups',
            new_name='Startup',
        ),
    ]
