# Generated by Django 3.1.2 on 2020-12-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_auto_20201204_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='../static/images/'),
        ),
    ]
