# Generated by Django 3.1.2 on 2020-12-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_startup_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
