# Generated by Django 3.1.2 on 2020-12-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_auto_20201206_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='startups/'),
        ),
    ]
